## Ejercicio 48

Si decimos que la ubicación de una página linkeada por otra es el promedio de la
latitud y longitud de los contenidos geolocalizados que la referencian: ¿Cuales son
las dos páginas que están más lejos? (⭐⭐⭐)

In [118]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
#Importo random para elegir cualquiera
import random as rd

In [119]:
geo_tags =  pd.read_csv('geo_tags.csv')
page_links = pd.read_csv('pagelinks_sample.csv',\
                       usecols=['pl_from','pl_title'])

In [120]:
geo_tags['gt_page_id'].value_counts()

7636249    1480
7421943    1424
9528315    1407
7808354    1396
8329856    1394
           ... 
4250460       1
72548         1
1119077       1
3236715       1
1048576       1
Name: gt_page_id, Length: 371411, dtype: int64

In [121]:
page_links.head()

pl_from                     pl_title
0  4840492  Bandera_código_del_COI_TPE
1   950948               Esteban_Dušan
2  6418187                      Insecta
3  3436623             Pleasure_to_Kill
4  4713066               Damián_Oliver

In [122]:
page_links.isnull().sum()

pl_from       0
pl_title    104
dtype: int64

In [123]:
page_links['pl_from'].value_counts()

2587499    18831
2389056    17495
2389124    17349
2389118    17344
2653364    16609
           ...  
7096870        1
2900519        1
7293510        1
8568058        1
9530785        1
Name: pl_from, Length: 6051413, dtype: int64

In [70]:
page_links['pl_title'].value_counts()

Zona_de_pruebas                   1131431
Wikidata                          1078031
Control_de_autoridades            1074385
Vandalismo                         922170
Contenidos                         577702
                                   ...   
Samaná_(municipio_colombiano)          1
(209669)_2005_CU56                      1
Mimi_Arnold_Wheeler                     1
ANALIA_FIORIO                           1
(399898)_2005_WA141                     1
Name: pl_title, Length: 7934362, dtype: int64

In [124]:
# Filtro los id que poseen geolocalizacion
geo_redirect_data = page_links.loc[page_links['pl_from'].isin(geo_tags['gt_page_id'])]
geo_redirect_data.head()

pl_from                  pl_title
7   2393385  Departamentos_de_Francia
13  1098340                  Wikidata
14  4574984     Localidades_de_Kansas
15  7034661    Control_de_autoridades
19  8429023               Dja-et-Lobo

In [125]:
geo_redirect_data.shape

(10385689, 2)

In [85]:
geo_tags.head()

gt_id  gt_page_id gt_globe  gt_primary   gt_lat   gt_lon  gt_dim gt_type  \
0   158041     4328020    earth           0  41.5075  -5.8175    1000     NaN   
1  5844377     4670424    earth           0  13.7380 -89.2920   10000    city   
2  5844381     4670424    earth           0  13.7020 -89.2080   10000    city   
3  5844383     4670424    earth           0  13.4000 -89.7500   10000    city   
4  5844388     4670424    earth           0  12.8500 -88.0000   10000    city   

  gt_name gt_country gt_region  
0     NaN        NaN       NaN  
1     NaN        NaN       NaN  
2     NaN        NaN       NaN  
3     NaN        NaN       NaN  
4     NaN        NaN       NaN

In [126]:
geo_redirect_data.rename(columns={'pl_from':'id'},inplace=True)
geo_tags = geo_tags[['gt_page_id','gt_lat','gt_lon']]
geo_tags.rename(columns={'gt_page_id':'id'},inplace=True)

C:\Users\alejo\anaconda3\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


In [127]:
merge_data = geo_redirect_data.merge(geo_tags,on='id')
merge_data.head()

id                          pl_title     gt_lat    gt_lon
0  2393385          Departamentos_de_Francia  46.313333  5.548889
1  2393385  Mapa_de_localización_de_Francia  46.313333  5.548889
2  2393385                     Código_INSEE  46.313333  5.548889
3  2393385                               CET  46.313333  5.548889
4  2393385       Distrito_de_Lons-le-Saunier  46.313333  5.548889

In [128]:
merge_data.isnull().sum()

id          0
pl_title    2
gt_lat      0
gt_lon      0
dtype: int64

In [129]:
merge_data.dropna(inplace=True)

In [130]:
merge_data.isnull().sum()

id          0
pl_title    0
gt_lat      0
gt_lon      0
dtype: int64

In [131]:
merge_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48442410 entries, 0 to 48442411
Data columns (total 4 columns):
 #   Column    Dtype  
---  ------    -----  
 0   id        int64  
 1   pl_title  object 
 2   gt_lat    float64
 3   gt_lon    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 1.8+ GB


In [134]:
merge_data['pl_title'] = merge_data['pl_title'].astype(str)

In [135]:
reduced_merge_data = merge_data.loc[merge_data['pl_title'].str.len() > 6]
reduced_merge_data

id                                 pl_title     gt_lat  \
0         2393385                 Departamentos_de_Francia  46.313333   
1         2393385         Mapa_de_localización_de_Francia  46.313333   
2         2393385                            Código_INSEE  46.313333   
4         2393385              Distrito_de_Lons-le-Saunier  46.313333   
5         2393385    Communauté_de_communes_de_Valous'Ain  46.313333   
...           ...                                      ...        ...   
48442405  9412557                      Paraná_(Argentina) -31.740603   
48442407  6952000                                 Wikidata  50.600000   
48442408  6952000                 Coordenadas_geográficas  50.600000   
48442410  7842764  Códigos_de_observatorios_astronómicos  35.202778   
48442411  1088977                                 Wikidata -40.803056   

              gt_lon  
0           5.548889  
1           5.548889  
2           5.548889  
4           5.548889  
5           5.548889  
...              ...  
48442405  -60.523258  
48442407   37.300000  
48442408   37.300000  
48442410 -111.664444  
48442411  -71.596111  

[44898066 rows x 4 columns]

In [136]:
grouped = reduced_merge_data.groupby(['pl_title']).agg({'gt_lat':'mean','gt_lon':'mean'})
grouped

gt_lat      gt_lon
pl_title                                                         
"El_don_de_la_Resurrección".               19.484444  -99.117222
"El_embarcadero"                            39.309722   -0.318333
"Ficha_de_persona"                          41.650000   -0.883333
"Guia_de_Arquitectura_de_Valencia"_CTAV     39.470978   -0.376303
"La_Barraca"                                39.309722   -0.318333
...                                               ...         ...
颜惠庆                                   25.038944  121.516328
駐日サウジアラビア王国大使館  35.625759  139.341531
高能物理研究所网                    56.746423   37.189268
魏道明                                   25.038944  121.516328
현내면                                   38.568083  128.389000

[1181639 rows x 2 columns]

In [145]:
coordenates = grouped[['gt_lat','gt_lon']].values
coordenates

array([[ 19.484444  , -99.117222  ],
       [ 39.30972222,  -0.31833333],
       [ 41.65      ,  -0.88333333],
       ...,
       [ 56.746423  ,  37.189268  ],
       [ 25.038944  , 121.516328  ],
       [ 38.56808333, 128.389     ]])

In [148]:
naam = NearestNeighbors(n_neighbors=2, algorithm='kd_tree').fit(coordenates)
distances, indices = naam.kneighbors(coordenates)

In [219]:
i = np.where(distances[:,1].flatten() ==  np.amin(distances[:,1].flatten()))
i

(array([      0,       1,       2, ..., 1181636, 1181637, 1181638],
       dtype=int64),)

In [220]:
indices[i]

array([[ 683750,  684095],
       [      4,       1],
       [ 207684, 1171079],
       ...,
       [ 452111, 1181636],
       [1181624, 1181595],
       [1181638,  262080]], dtype=int64)

In [221]:
#Importo random para elegir cualquiera
import random as rd

In [230]:
ran = rd.randint(0,len(i[0]))
# Los dos mas cercanos seran
grouped.iloc[indices[ran]]

gt_lat  gt_lon
pl_title                              
Museo_de_Port_Louis -20.166667    57.5
Fiscal_General      -20.166667    57.5